-- =========================================
-- FIXED SCHEMA (PostgreSQL)
-- =========================================

-- DROP TABLE IF EXISTS bewertung, buchung_zimmer, buchung, zimmer_bild, zimmer, zimmertyp,
--                      hotel_ausstattung, ausstattung, hotel_bild, hotel, hotelbesitzer, kunde, benutzer
--                      CASCADE;

CREATE TABLE IF NOT EXISTS benutzer (
  benutzer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       VARCHAR NOT NULL,
  vorname     VARCHAR NOT NULL,
  nachname    VARCHAR NOT NULL,
  land        VARCHAR NOT NULL,
  strasse     VARCHAR NOT NULL,
  plz         VARCHAR NOT NULL,
  ort         VARCHAR NOT NULL,
  passwort_hash VARCHAR NOT NULL,
  CONSTRAINT uq_benutzer_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS kunde (
  benutzer_id INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS hotelbesitzer (
  benutzer_id INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS hotel (
  hotel_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  besitzer_id INT NOT NULL,
  name VARCHAR NOT NULL,
  beschreibung TEXT NOT NULL,
  hotelsterne INT NOT NULL,
  land VARCHAR NOT NULL,
  strasse VARCHAR NOT NULL,
  plz VARCHAR NOT NULL,
  ort VARCHAR NOT NULL,
  stornogebuehr_prozent INT NOT NULL,
  kostenlos_stornierbar_bis_stunden INT NOT NULL,
  latitude NUMERIC(10,8),
  longitude NUMERIC(11,8),
  slug VARCHAR NOT NULL UNIQUE,
  status VARCHAR NOT NULL DEFAULT 'active',

  CONSTRAINT chk_hotelsterne CHECK (hotelsterne BETWEEN 1 AND 5),
  CONSTRAINT chk_storno_prozent CHECK (stornogebuehr_prozent BETWEEN 0 AND 100),
  CONSTRAINT chk_kostenlos_storno_stunden CHECK (kostenlos_stornierbar_bis_stunden >= 0),
  CONSTRAINT chk_status CHECK (status IN ('active', 'deactivated'))
);

CREATE TABLE IF NOT EXISTS hotel_bild (
  hotel_bild_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id INT NOT NULL,
  pfad VARCHAR NOT NULL,
  alt_text VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS ausstattung (
  ausstattung_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titel VARCHAR NOT NULL,
  beschreibung TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hotel_ausstattung (
  hotel_id INT NOT NULL,
  ausstattung_id INT NOT NULL,
  PRIMARY KEY (hotel_id, ausstattung_id)
);

CREATE INDEX IF NOT EXISTS hotel_ausstattung_index_0
ON hotel_ausstattung (hotel_id, ausstattung_id);

CREATE TABLE IF NOT EXISTS zimmertyp (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bezeichnung VARCHAR NOT NULL,
  CONSTRAINT uq_zimmertyp_bezeichnung UNIQUE (bezeichnung)
);

CREATE TABLE IF NOT EXISTS zimmer (
  zimmer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id INT NOT NULL,
  zimmernr_hotel VARCHAR NOT NULL,
  bezeichnung VARCHAR NOT NULL,
  beschreibung TEXT NOT NULL,
  basispreis DECIMAL(10,2) NOT NULL,
  max_anzahl INT NOT NULL,
  zimmertyp_id INT NOT NULL,

  CONSTRAINT chk_zimmer_max_anzahl CHECK (max_anzahl > 0),
  CONSTRAINT chk_zimmer_basispreis CHECK (basispreis >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS zimmer_index_1
ON zimmer (hotel_id, zimmernr_hotel);

CREATE TABLE IF NOT EXISTS zimmer_bild (
  zimmer_bild_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zimmer_id INT NOT NULL,
  pfad VARCHAR NOT NULL,
  alt_text VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS zahlungsmethode (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bezeichnung VARCHAR NOT NULL,
  CONSTRAINT uq_zahlungsmethode_bezeichnung UNIQUE (bezeichnung)
);

CREATE TABLE IF NOT EXISTS buchung (
  buchungs_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kunde_id INT NOT NULL,
  buchungsdatum DATE NOT NULL,
  checkin DATE NOT NULL,
  checkout DATE NOT NULL,
  stornodatum DATE,
  anzahl_gaeste INT NOT NULL,
  preis_pro_nacht DECIMAL(10,2) NOT NULL,
  zahlungsmethode_id INT NOT NULL,
  zahlungsdatum DATE NOT NULL,

  CONSTRAINT chk_buchung_gaeste CHECK (anzahl_gaeste > 0),
  CONSTRAINT chk_buchung_preis CHECK (preis_pro_nacht >= 0),
  CONSTRAINT chk_buchung_daten CHECK (checkout > checkin),
  CONSTRAINT chk_buchung_storno CHECK (stornodatum IS NULL OR stornodatum >= buchungsdatum)
);

-- =========================
-- FIX: buchung_zimmer Spaltennamen "clean"
-- =========================
CREATE TABLE IF NOT EXISTS buchung_zimmer (
  buchungs_id INT NOT NULL,
  zimmer_id INT NOT NULL,
  anzahl_gaeste INT NOT NULL,
  preis_pro_nacht DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (buchungs_id, zimmer_id),

  CONSTRAINT chk_bz_gaeste CHECK (anzahl_gaeste > 0),
  CONSTRAINT chk_bz_preis CHECK (preis_pro_nacht >= 0)
);

CREATE INDEX IF NOT EXISTS buchung_zimmer_index_2
ON buchung_zimmer (buchungs_id, zimmer_id);

CREATE TABLE IF NOT EXISTS bewertung (
  buchungs_id INT PRIMARY KEY,
  titel VARCHAR NOT NULL,
  text TEXT NOT NULL,
  sterne INT NOT NULL,
  CONSTRAINT chk_bewertung_sterne CHECK (sterne BETWEEN 1 AND 5)
);

COMMENT ON TABLE bewertung IS 'Bewertung gehört zu genau einer Buchung; sterne 1..5';

-- =========================================
-- CORRECT FOREIGN KEYS (Child -> Parent)
-- =========================================

-- Spezialisierung: Kunde/Hotelbesitzer sind Benutzer
ALTER TABLE kunde
  ADD CONSTRAINT fk_kunde_benutzer
  FOREIGN KEY (benutzer_id) REFERENCES benutzer(benutzer_id)
  ON DELETE CASCADE;

ALTER TABLE hotelbesitzer
  ADD CONSTRAINT fk_hotelbesitzer_benutzer
  FOREIGN KEY (benutzer_id) REFERENCES benutzer(benutzer_id)
  ON DELETE CASCADE;

-- Hotel gehört einem Hotelbesitzer
ALTER TABLE hotel
  ADD CONSTRAINT fk_hotel_besitzer
  FOREIGN KEY (besitzer_id) REFERENCES hotelbesitzer(benutzer_id)
  ON DELETE RESTRICT;

-- Hotelbilder gehören zu Hotel
ALTER TABLE hotel_bild
  ADD CONSTRAINT fk_hotelbild_hotel
  FOREIGN KEY (hotel_id) REFERENCES hotel(hotel_id)
  ON DELETE CASCADE;

-- Zimmer gehören zu Hotel + Zimmertyp
ALTER TABLE zimmer
  ADD CONSTRAINT fk_zimmer_hotel
  FOREIGN KEY (hotel_id) REFERENCES hotel(hotel_id)
  ON DELETE CASCADE;

ALTER TABLE zimmer
  ADD CONSTRAINT fk_zimmer_zimmertyp
  FOREIGN KEY (zimmertyp_id) REFERENCES zimmertyp(id)
  ON DELETE RESTRICT;

-- Zimmerbilder gehören zu Zimmer
ALTER TABLE zimmer_bild
  ADD CONSTRAINT fk_zimmerbild_zimmer
  FOREIGN KEY (zimmer_id) REFERENCES zimmer(zimmer_id)
  ON DELETE CASCADE;

-- m:n Hotel-Ausstattung
ALTER TABLE hotel_ausstattung
  ADD CONSTRAINT fk_hotel_ausstattung_hotel
  FOREIGN KEY (hotel_id) REFERENCES hotel(hotel_id)
  ON DELETE CASCADE;

ALTER TABLE hotel_ausstattung
  ADD CONSTRAINT fk_hotel_ausstattung_ausstattung
  FOREIGN KEY (ausstattung_id) REFERENCES ausstattung(ausstattung_id)
  ON DELETE CASCADE;

-- Buchung gehört zu Kunde + Zahlungsmethode
ALTER TABLE buchung
  ADD CONSTRAINT fk_buchung_kunde
  FOREIGN KEY (kunde_id) REFERENCES kunde(benutzer_id)
  ON DELETE RESTRICT;

ALTER TABLE buchung
  ADD CONSTRAINT fk_buchung_zahlungsmethode
  FOREIGN KEY (zahlungsmethode_id) REFERENCES zahlungsmethode(id)
  ON DELETE RESTRICT;

-- m:n Buchung-Zimmer
ALTER TABLE buchung_zimmer
  ADD CONSTRAINT fk_buchung_zimmer_buchung
  FOREIGN KEY (buchungs_id) REFERENCES buchung(buchungs_id)
  ON DELETE CASCADE;

ALTER TABLE buchung_zimmer
  ADD CONSTRAINT fk_buchung_zimmer_zimmer
  FOREIGN KEY (zimmer_id) REFERENCES zimmer(zimmer_id)
  ON DELETE RESTRICT;

-- Bewertung gehört 1:1 zu Buchung
ALTER TABLE bewertung
  ADD CONSTRAINT fk_bewertung_buchung
  FOREIGN KEY (buchungs_id) REFERENCES buchung(buchungs_id)
  ON DELETE CASCADE;